### ISSUE TITLE
Critical error message : No non-console-based loggers configured

### ISSUE THREAD

**Issue by chiaweh2** [NOAA-GFDL/MDTF-diagnostics#156] opened 2021-03-01 01:42 UTC
After updating to the newest version with changes suggested in the PR, the integration with my POD seems to break. The program seems to stop before generating the log file. The error message seems to show not getting the POD name. The error can be reproduced in the newest commit  5979800 #107 

Below is the error message
```
(base) -bash-4.1$ ./mdtf -f src/default_tests.jsonc
=== Starting /storage1/home1/chiaweih/mdtf/MDTF-diagnostics/mdtf_framework.py

PACKAGE SETTINGS:
  case_list(0):
    CASENAME: CESM2_omip1_r1i1p1f1_gn
    model: CESM2
    convention: CESM
    FIRSTYR: 1993
    LASTYR: 2009
    pod_list:
      tropical_pacific_sea_level
    experiment: ""
  paths:
    CODE_ROOT: /storage1/home1/chiaweih/mdtf/MDTF-diagnostics
    OBS_DATA_ROOT: /storage1/home1/chiaweih/mdtf/inputdata/obs_data
    MODEL_DATA_ROOT: /storage1/home1/chiaweih/mdtf/inputdata/model
    WORKING_DIR: /storage1/home1/chiaweih/mdtf/wkdir
    OUTPUT_DIR: /storage1/home1/chiaweih/mdtf/wkdir
    conda_root: /storage1/home1/chiaweih/anaconda2
    conda_env_root: /storage1/home1/chiaweih/anaconda2/envs
    TEMP_DIR_ROOT: /storage1/home1/chiaweih/mdtf/wkdir
  settings:
    environment_manager: Conda
    runtime_manager: subprocess
    output_manager: html
    save_ps: true
    make_variab_tar: true
    convention: CMIP
    data_manager: Local_File
    file_transfer_timeout: 300
  env_vars:
    RGB: /storage1/home1/chiaweih/mdtf/MDTF-diagnostics/shared/rgb
    MPLBACKEND: Agg
### Framework: initialize CESM2_omip1_r1i1p1f1_gn
WARNING: No non-console-based loggers configured.
CRITICAL: **********************************************************************
Uncaught exception:
Traceback (most recent call last):
  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/mdtf_framework.py", line 72, in <module>
    exit_code = main()
  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/mdtf_framework.py", line 68, in main
    exit_code = framework.main()
  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/core.py", line 245, in main
    case.setup()
  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/data_manager.py", line 345, in setup
    for pod_name in self.pods
  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/data_manager.py", line 345, in <dictcomp>
    for pod_name in self.pods
  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/diagnostic.py", line 493, in from_config
    return cls.from_struct(pod_name, config.pod_data[pod_name])
KeyError: 'tropical_pacific_sea_level'
```

**Comment by wrongkindofdoctor** [comment] 2021-03-01 18:40
@chiaweh2 The missing console logger is triggering a warning, but doesn't appear to be causing the failure. I can replicate the error, but don't know the source yet (will probably need input from @tsjackson-noaa). Possible causes I can think of: 
* missing info/typo in a config file somewhere (the settings.jsonc file for the tropical pacific sea level pod looks okay at first glance, though)
* issue with the POD name parser

**Comment by chiaweh2** [comment] 2021-03-02 15:59
@wrongkindofdoctor  Thank you! I will double check the config file format. I do have one question related to the model input file name and location. Currently my "path_variable" is set to "VAR_FILE" for each variable. Does this mean the MDTF framework will locate my model input file automatically based on the MODEL_DATA_ROOT, CASENAME, frequency, and variable name?

**Comment by wrongkindofdoctor** [comment] 2021-03-02 19:37
@chiaweh2 I'm not sure if the path variable affects anything, but the framework checks `MODEL_DATA_ROOT` for the input files, and uses the information in the default_tests.jsonc and POD settings.jsonc (variable names, frequency, etc...) files to narrow down what to read in from the input files. The [Walkthrough of the Framework Operation section](https://github.com/wrongkindofdoctor/MDTF-diagnostics/blob/develop/doc/sphinx/dev_walkthrough.rst#step-2-data-request) of the documentation provides more details about the input data processing.

**Comment by tsjackson-noaa** [comment] 2021-03-06 04:26
Hi @chiaweh2 -- we discussed this problem in our group meeting this past week. The critical error is due to the package not being able to find your POD. Since the error is happening very early in the package's execution, it would seem that you're either missing

- a directory named `tropical_pacific_sea_level` in the `diagnostics` directory of the code, or
- a file named `settings.jsonc` in that directory describing your POD, formatted as in the example POD,
- which doesn't have syntax errors (you can paste the contents of `settings.jsonc` file into https://codebeautify.org/json5-validator to check for syntax errors -- "json5" is a synonym for "jsonc"/JSON with comments.)

but it sounds like you've done this. I'll work more with @wrongkindofdoctor to attempt to reproduce this problem -- it may be that other error messages are being generated but not displayed.

**Comment by chiaweh2** [comment] 2021-03-08 17:35
Hi @tsjackson-noaa @wrongkindofdoctor -- thank you! Yes I did double check the format. It shows a valid josn5 format. The directory name and settings.jsonc file seem to be in place and correct.

**Comment by briansoden** [comment] 2021-03-15 14:03
Hi @chiaweh2 @tsjackson-noaa @wrongkindofdoctor, just jumping in to say we've run into the exact same error at seemingly the same spot in the execution.  This only started to happen when we switched to the latest package version and updated our POD accordingly. As far as I can tell, we've correctly followed all the formatting @tsjackson-noaa mentions above.

I was going to hold off on a new pull request until we worked out this bug, but I can upload our latest version now if that would be helpful.  Thanks!

**Comment by briansoden** [comment] 2021-04-06 14:01
Hi @tsjackson-noaa @wrongkindofdoctor has the Leads Team been able to make any progress with figuring out this error?  @chiaweh2 and our group haven't on our end.

**Comment by wrongkindofdoctor** [comment] 2021-04-06 14:35
@briansoden Thanks for the reminder to investigate this issue. Go ahead and submit the PR as a draft (clicking the little arrow icon to the right of the submit pull request button will display a dropdown with the option for a draft), since this will make it easier to review possible changes that might be creating the issues.

**Comment by jkrasting** [comment] 2021-04-06 20:47
@briansoden - I have some news to report from testing this late last week with @chiaweh2's POD.  This error is definitely symptomatic of a syntax error in your POD's jsonc file.  Here is an example with what I had to do with the tropical sea level POD:  https://github.com/jkrasting/MDTF-diagnostics/commit/f89fa8b39049d6f1b9a09fd085e14ea2d2e87436

There was a trailing "," in one of the lines that I caught with an [online json validator](https://jsonlint.com).  I would recommend starting here to make sure that you have a valid json file.  I found that this is a silent error that occurs in the framework that we should definitely address.  See #179. The framework should make some noise when there is a json syntax issue.


The sea level POD's json file also had this line that I ended up deleting:  `"dimensions_ordered": true`. @wrongkindofdoctor and @tsjackson-noaa - can you comment if this line should in fact be deleted from the json files?

**Comment by wrongkindofdoctor** [comment] 2021-04-06 21:50
According to the documentation, there is no "dimensions_ordered" key for variables in the settings.jsonc file, so it can be safely deleted provided that it is not a separate environment variable parsed by the POD.

**Comment by briansoden** [comment] 2021-04-07 15:20
Thanks, @jkrasting.  We had "dimensions_ordered" as well in our json file, and getting rid of it seemed to do the trick. And thanks for the json validator. We had a missing quote somewhere in there too. Fixing this error has, of course, revealed another error down the line, so we'll address that and then submit a new PR hopefully soon. I'll post elsewhere in the Issues list if we have trouble, though.

**Comment by jkrasting** [comment] 2021-04-15 14:59
PR (#185) does correct the static variable issue - thanks @wrongkindofdoctor!

**Comment by jkrasting** [comment] 2021-04-15 15:01
Closing as this issue is a duplicate of #164.

**Closed by jkrasting** 2021-04-15 15:01 UTC
Labels: bug
