### ISSUE TITLE
Empty mdtf log

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/MDTF-diagnostics#195] opened 2021-04-16 15:19 UTC
I am working on a new POD, and am trying to debug. I see when I attempt to run the framework, in the output folder within /wkdir there is mdtf.log which I thought might give me some ideas as to why my POD fails. However it is blank. 

Might I have missed a step somewhere in setting up the POD which is preventing this log from working?

_Originally posted by @drewmresnick in https://github.com/NOAA-GFDL/MDTF-diagnostics/discussions/192_

**Comment by wrongkindofdoctor** [comment] 2021-04-16 15:21
If you can provide the commands you entered, terminal output, and the updated branch you are working on, we can help you solve the issue.

**Comment by bitterbark** [comment] 2021-04-18 20:27
I also am gettting an empty mdtf.log; all of the output is going to the $OUTDIR/$POD_NAME/pod_name.log file
Do you have output in that/those?

**Comment by tsjackson-noaa** [comment] 2021-04-20 01:32
Hi @bitterbark  and @drewmresnick:
Thanks for reporting this bug. Unfortunately I haven't been able to reproduce it, since I still get a log file after forcing a POD to exit with errors. 

Currently I don't have many guesses, since the overall log file is created before any of the POD-specific log files, and anything written to stdout or stderr should also be in the file (under the default configuration). I'd say the log file isn't being created for some reason -- this can be checked by running the framework at debug level (`-v`) and checking for a line that says "Contents of log cache transferred" in the console output (right after the input configuration is echoed).

Another thing to try would be checking out the [feature/disable-preproc](https://github.com/NOAA-GFDL/MDTF-diagnostics/tree/feature/disable-preproc) branch and running your POD with it -- the code in this branch contains significant changes to how logging is configured, and may fix this bug without having to narrow down its cause. No change is needed to the POD's code or settings file, but note that the log file has been renamed from `mdtf.log` to `$CASENAME.log`.

**Comment by jkrasting** [comment] 2021-04-20 12:14
I have been able to reproduce this using the tropical sea level POD.  @tsjackson-noaa - try using [this branch](https://github.com/jkrasting/MDTF-diagnostics/tree/trop_sl_rebased) and comment out the metadata checking in[ lines 1100-1123 of the data manager](https://github.com/jkrasting/MDTF-diagnostics/blob/trop_sl_rebased/src/data_manager.py#L1100-L1123).  This triggered the POD to run and fail.  No errors are reported to the stdout but you should see some environment variable issues in the log file specific to the POD.  (My test data is in $HOME/mdtf/inputdata)

**Comment by drewmresnick** [comment] 2021-04-23 00:07
I do get an output in `$CASENAME.log` now. Is there a reason that mdtf.log is generated? Should there theoretically be different information printing to that log than in `$CASENAME.log` ?

**Comment by wrongkindofdoctor** [comment] 2021-04-27 14:48
@drewmresnick As I understand it, the mdtf.log contains the framework-specific output, while the $CASENAME.log has the POD-specific output (though there may be some overlap depending on how the messages are classified). @tsjackson-noaa can set me straight if I'm missing something.

**Comment by bitterbark** [comment] 2021-04-28 19:43
It looks to me like the pod-specific output goes into
$OUTPUT_DIR/$PODNAME/$PODNAME.log

**Closed** 2021-09-24 14:55 UTC
Labels: bug, framework
