### ISSUE TITLE
XQuartz is a required dependency for NCL-based PODs on Mac OS

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MDTF-diagnostics#65] opened 2020-11-12 16:09 UTC
The MJO_teleconnection POD is failing for me with the following error:

```
('Calling ', '/User/mdtf/MDTF-diagnostics/diagnostics/MJO_teleconnection/mjo_diag_RMM_MDTF.ncl')
dyld: Library not loaded: /opt/X11/lib/libcairo.2.dylib
  Referenced from: /User/miniconda3/envs/_MDTF_NCL_base/bin/ncl
  Reason: image not found
NCL routine /User/mdtf/MDTF-diagnostics/diagnostics/MJO_teleconnection/mjo_diag_RMM_MDTF.ncl
```

This is based on a fresh install this morning and running the basic test:

```
./mdtf -f src/default_tests.jsonc
```

@tsjackson-noaa - does this work on your Mac?

@wrongkindofdoctor, @tsjackson-noaa - is there a Travis build option to test this out specifically on the latest Mac OS?  Any other ideas on how to trap this?

Any thoughts on how to address this, or are we dependent on the NCL team to update their package?

**Comment by wrongkindofdoctor** [comment] 2020-11-12 22:56
I would inform the NCL team that they need to upgrade their code.

**Comment by jkrasting** [comment] 2020-11-12 23:02
Thanks @wrongkindofdoctor - @bitterbark, do you have a contact over there to ping about this?

**Comment by tsjackson-noaa** [comment] 2020-11-13 20:50
Hi @jkrasting -- I'm also running Catalina, but I haven't been able to reproduce the error (via running MJO_teleconnection from the `develop` branch on the QBOi.EXP1.AMIP.001 sample data). For what it's worth, I do have libcairo at the path referenced in the error message (from XQuartz), so that might be why I never encountered it. This NCL [support thread](https://mailman.ucar.edu/pipermail/ncl-install/2019-November/002864.html) would seem to support this.

On the other hand, Cairo is a [required dependency](http://www.ncl.ucar.edu/Download/build_from_src.shtml#cairo) of NCL, so I'd be surprised that such a critical bug would go unfixed in the conda recipe. conda-forge has cairo, as well as a lot of X.org stuff, so there wouldn't seem to be an obstacle to delivering these dependencies via conda (instead of telling the user to manually install XQuartz first, which is what all the support threads I'm coming across are saying to do.) We would've also hit this bug earlier, running any of the other PODs that use NCL -- nothing should have changed recently: our environment specifies NCL version 6.6.2 (still the most recent) and the conda-forge recipe for it hasn't changed in the last 7 months.

The only other thing I can think of that might be relevant is mac os' System Integrity Protection: since conda runs with user privileges, when it goes to install `cairo` it may be putting the libs somewhere other than `/opt/X11/lib` and putting that location on `DYLD_LIBRARY_PATH` or `DYLD_FALLBACK_LIBRARY_PATH`, but in order to prevent malicious code injection, System Integrity Protection [unsets these shell variables](https://apple.stackexchange.com/questions/212945/unable-to-set-dyld-fallback-library-path-in-shell-on-osx-10-11-1). Apparently it started doing that back in mac os 10.11, though, so again I'm not sure why we're seeing it now, and it looks like the NCL executable's path to the cairo libs is hard-coded, rather than set dynamically, anyway.

1. Could you try reinstalling the conda environment, if you haven't already? (`conda env create --force -f src/conda/env_NCL_base.yml`.) `conda list` then shows that `cairo` 1.16.0 is installed.`` otool -L `which ncl` `` will list the libraries the NCL executable is linked to. 

2. I still have my Travis account configured, so I'll try to reproduce the bug on one of their mac os instances -- the Travis script runs EOF_500hPa, which uses NCL.

3. Kind of out of ideas otherwise -- really want to avoid having to tell users on macs that they need to install XQuartz first, as I think our installation instructions involve too many steps as it is.

**Comment by jkrasting** [comment] 2020-11-13 21:43
Thanks @tsjackson-noaa.  Here's what I found.  `cairo == 1.16.0`

(I'm a glutton for punishment - I'm going to advance to Big Sur tonight.)

```
conda activate _MDTF_NCL_base
(_MDTF_NCL_base)  [~] $ conda list | grep cairo
cairo                     1.16.0            hec6a9b0_1003    conda-forge
(_MDTF_NCL_base) [~] $ otool -L `which ncl`
$USER/miniconda3/envs/_MDTF_NCL_base/bin/ncl:
	@rpath/libnetcdf.15.dylib (compatibility version 15.0.0, current version 15.0.0)
	@rpath/libcurl.4.dylib (compatibility version 10.0.0, current version 10.0.0)
	@rpath/libhdf5_hl.100.dylib (compatibility version 102.0.0, current version 102.2.0)
	@rpath/libhdf5.103.dylib (compatibility version 105.0.0, current version 105.0.0)
	@rpath/libmfhdf.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libdf.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libjpeg.9.dylib (compatibility version 13.0.0, current version 13.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	@rpath/libgdal.26.dylib (compatibility version 27.0.0, current version 27.2.0)
	@rpath/libproj.15.dylib (compatibility version 18.0.0, current version 18.1.0)
	@rpath/libudunits2.0.dylib (compatibility version 2.0.0, current version 2.0.0)
	@rpath/libexpat.1.dylib (compatibility version 8.0.0, current version 8.7.0)
	@rpath/libjasper.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	@rpath/libpng16.16.dylib (compatibility version 54.0.0, current version 54.0.0)
	/opt/X11/lib/libcairo.2.dylib (compatibility version 11403.0.0, current version 11403.6.0)
	/opt/X11/lib/libfontconfig.1.dylib (compatibility version 11.0.0, current version 11.2.0)
	/opt/X11/lib/libpixman-1.0.dylib (compatibility version 35.0.0, current version 35.0.0)
	/opt/X11/lib/libfreetype.6.dylib (compatibility version 19.0.0, current version 19.6.0)
	/opt/X11/lib/libXrender.1.dylib (compatibility version 5.0.0, current version 5.0.0)
	@rpath/libiconv.2.dylib (compatibility version 9.0.0, current version 9.0.0)
	@rpath/libbz2.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	@rpath/libgsl.23.dylib (compatibility version 25.0.0, current version 25.0.0)
	@rpath/libcblas.3.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/X11/lib/libXpm.4.dylib (compatibility version 16.0.0, current version 16.0.0)
	/opt/X11/lib/libX11.6.dylib (compatibility version 10.0.0, current version 10.0.0)
	/opt/X11/lib/libXext.6.dylib (compatibility version 11.0.0, current version 11.0.0)
	@rpath/libgfortran.4.dylib (compatibility version 5.0.0, current version 5.0.0)
	@rpath/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libomp.dylib (compatibility version 5.0.0, current version 5.0.0)
	@rpath/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by jkrasting** [comment] 2020-11-22 15:02
This is indeed related to XQuartz.  I did not have it installed on my system after I had done a fresh OS install a few weeks ago.  I am thinking we should add this to the documentation.

We also need a test to detect if XQuartz is installed.  Is it sufficient to test if this directory exists `/opt/X11/lib/`, e.g.:

```
import platform
import os

if platform.system() == "Darwin":
    assert os.path.exists("/opt/X11/lib"), "XQuartz is a required dependency for running MDTF on Mac OS."
```

**Comment by tsjackson-noaa** [comment] 2021-06-11 17:06
Closing this issue since #234 has been merged.

**Closed by tsjackson-noaa** 2021-06-11 17:06 UTC
Labels: bug, docs-policy
