### ISSUE TITLE
Add a pull request template with a checklist of merge criteria

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/MDTF-diagnostics#62] opened 2020-11-03 20:12 UTC
Github supports templates for[ pull requests (and issues)](https://github.blog/2016-02-17-issue-and-pull-request-templates/) that can include a checklist with criteria (see the [FMS PR template](https://github.com/NOAA-GFDL/FMS/blob/master/.github/PULL_REQUEST_TEMPLATE.md) for an example). We can stipulate that contributors must check all of the boxes before their PR is reviewed and merged. I'm tagging you, @yihungkuo, since @jkrasting mentioned that your input on the associated PR would be helpful.

**Comment by tsjackson-noaa** [comment] 2021-02-03 04:01
Closing this since PR #63 was merged and checklist is working as intended.

**Closed by tsjackson-noaa** 2021-02-03 04:01 UTC
Labels: docs-policy, feature-request
